create table cafeteria_item
(
    id         bigint generated by default as identity,
    name       varchar(255)             not null,
    price      numeric(12, 2)           not null,
    created_at timestamp with time zone not null,
    primary key (id)
);